### ISSUE TITLE
Cant not Accept Trade

### ISSUE THREAD

**Issue by voz261** [waylaidwanderer/SteamTradeOffersBot#25] opened 2018-04-11 12:47 UTC
Can you check this error , thank sm

Cant not Accept Trade

> Unhandled Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
> 
> TradeOffers.cs:line 96 
![bug bot](https://user-images.githubusercontent.com/4730177/38617393-1c03f516-3dc1-11e8-9ed8-50f20ff94622.png)

**Comment by Koenig4443** [comment] 2018-04-11 23:42
this is not related to #1108

This error is caused by steam now forcing a redirect from http to https. it can be fixed by simply changing the url in AcceptTrade(TradeOffer tradeOffer, out ulong tradeId) to https .

AcceptTradeis located in TradeOffers.cs from SteamAPI project

just to be sure i changed all urls to https

**Closed as completed** 2018-04-12 00:00 UTC
